# DigitalOcean App Platform Configuration
# This file defines how your app will be deployed on DigitalOcean App Platform

name: template-management-app
region: nyc

# Database configuration
databases:
  - engine: PG
    name: main-db
    production: true
    version: "15"

# Services configuration
services:
  # Backend API Service
  - name: backend
    environment_slug: node-js
    github:
      repo: YOUR_GITHUB_USERNAME/YOUR_REPO_NAME
      branch: main
      deploy_on_push: true
    source_dir: /backend
    
    # Build configuration
    build_command: npm ci
    
    # Run configuration
    run_command: npm start
    
    # Environment variables
    envs:
      - key: NODE_ENV
        value: "production"
      - key: PORT
        value: "8080"
      - key: JWT_SECRET
        scope: RUN_AND_BUILD_TIME
        type: SECRET
      - key: FRONTEND_URL
        value: "${frontend.PUBLIC_URL}"
      - key: DATABASE_URL
        value: "${main-db.DATABASE_URL}"
        type: SECRET
    
    # Health check
    health_check:
      http_path: /api/health
      initial_delay_seconds: 30
      period_seconds: 10
      timeout_seconds: 5
      success_threshold: 1
      failure_threshold: 3
    
    # Instance configuration
    instance_count: 1
    instance_size_slug: basic-xxs
    
    # HTTP configuration
    http_port: 8080
    
    routes:
      - path: /api

  # Frontend Static Site
  - name: frontend
    environment_slug: node-js
    github:
      repo: YOUR_GITHUB_USERNAME/YOUR_REPO_NAME
      branch: main
      deploy_on_push: true
    source_dir: /frontend
    
    # Build configuration
    build_command: npm ci && npm run build
    
    # Output directory (Vite builds to 'dist')
    output_dir: dist
    
    # Environment variables for build
    envs:
      - key: VITE_API_URL
        value: "${backend.PUBLIC_URL}/api"
    
    # Instance configuration (static sites use different config)
    instance_count: 1
    instance_size_slug: basic-xxs
    
    routes:
      - path: /
    
    # Static site configuration
    static_sites:
      - name: frontend
        build_command: npm ci && npm run build
        output_dir: dist
        catchall_document: index.html
        routes:
          - path: /

# Optional: Workers (if needed for background jobs)
# workers:
#   - name: worker
#     environment_slug: node-js
#     github:
#       repo: YOUR_GITHUB_USERNAME/YOUR_REPO_NAME
#       branch: main
#     source_dir: /backend
#     build_command: npm ci
#     run_command: node src/worker.js

# Optional: Jobs (for scheduled tasks)
# jobs:
#   - name: cleanup-job
#     kind: PRE_DEPLOY
#     environment_slug: node-js
#     github:
#       repo: YOUR_GITHUB_USERNAME/YOUR_REPO_NAME
#       branch: main
#     source_dir: /backend
#     build_command: npm ci
#     run_command: node src/jobs/cleanup.js

