# DigitalOcean App Platform Specification
# Template Management Dashboard
# This file defines how to deploy both frontend and backend

name: template-management-dashboard

region: nyc

# ===========================================
# BACKEND SERVICE (Node.js API)
# ===========================================
services:
  - name: api
    github:
      repo: YOUR_GITHUB_USERNAME/YOUR_REPO_NAME
      branch: main
      deploy_on_push: true
    source_dir: backend
    environment_slug: node-js
    instance_count: 1
    instance_size_slug: apps-s-1vcpu-0.5gb
    http_port: 3001
    routes:
      - path: /api
      - path: /socket.io
    envs:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: "3001"
      - key: DATABASE_URL
        scope: RUN_TIME
        value: ${db.DATABASE_URL}
      - key: JWT_SECRET
        scope: RUN_TIME
        type: SECRET
        value: CHANGE_THIS_TO_A_STRONG_SECRET
      - key: FRONTEND_URL
        scope: RUN_TIME
        value: ${APP_URL}
    build_command: npm install
    run_command: npm start
    health_check:
      http_path: /api/health

# ===========================================
# FRONTEND SERVICE (React Static Site)
# ===========================================
static_sites:
  - name: frontend
    github:
      repo: YOUR_GITHUB_USERNAME/YOUR_REPO_NAME
      branch: main
      deploy_on_push: true
    source_dir: frontend
    build_command: npm install && npm run build
    output_dir: dist
    envs:
      - key: VITE_API_URL
        scope: BUILD_TIME
        value: ${api.PUBLIC_URL}/api
    routes:
      - path: /
    catchall_document: index.html

# ===========================================
# DATABASE (Managed PostgreSQL)
# ===========================================
databases:
  - name: db
    engine: PG
    production: false
    cluster_name: template-db
    db_name: template_management
    db_user: template_user

